/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ActionBar: typeof import('./src/components/ActionBar.vue')['default']
    DarkSwitcher: typeof import('./src/components/DarkSwitcher.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
    TheTest: typeof import('./src/components/TheTest.vue')['default']
    TimeSchedular: typeof import('./src/components/TimeSchedular.vue')['default']
    TimezoneSearchBar: typeof import('./src/components/TimezoneSearchBar.vue')['default']
  }
}
